thinkful-wikiful-bdd/config/routes.rb
Rails.application.routes.draw do 
  get   'articles/autocomplete_authors',      
                                to: 'articles#autocomplete_authors',
                                                        as: :articles_autocomplete_authors

  get   'articles/search',      to: 'articles#search',  as: :articles_search
  post  'articles/search',      to: 'articles#search'

  resources :articles
  
  post  'articles/author(/:author)',  to: 'articles#author', as: :articles_author
  post  'articles/date(/:date)',      to: 'articles#date',   as: :articles_date

  get   'login',  to: 'sessions#new',     as: :login
  post  'login',  to: 'sessions#create'

  get   'logout', to: 'sessions#destroy', as: :logout

  get   'signup', to: 'users#new',        as: :signup
  post  'signup', to: 'users#create'

  root to: 'home#index'
end

thinkful-wikiful-bdd/app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user

  has_many :article_categories
  has_many :categories, through: :article_categories

  validates_length_of :title , minimum: 3, maximum: 128
  validates_length_of :content, minimum: 3, maximum: 64000

  #validates_presence_of :user
  validates_presence_of :categories

  def self.find_by_author_id(id)
    Article.order(created_at: :desc).where(user_id: id)
  end

  def self.find_by_author_user_name(user_name)
    user = User.where('lower(user_name) = ?', user_name.downcase).first
    return [] if user.nil?
    user.articles
  end

  def self.find_by_author_name(name)
    user = User.where('lower(name) = ?', name.downcase).first
    return [] if user.nil?
    user.articles
  end

  def self.find_by_date_published(date_published)
    Article.where('extract(month from created_at) = ? AND extract(day from created_at) = ? AND extract(year from created_at) = ?', 
      date_published.month, date_published.day, date_published.year)
  end
end

thinkful-wikiful-bdd/app/models/article_category.rb
class ArticleCategory < ActiveRecord::Base
  attr_accessor :article_id, :category_id

  belongs_to :article 
  belongs_to :category
end

thinkful-wikiful-bdd/app/models/category.rb
class Category < ActiveRecord::Base

  has_many :article_categories
  has_many :articles, through: :article_categories

  validates_length_of :name, minimum: 3, maximum: 16
end

thinkful-wikiful-bdd/app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password

  validates_length_of :name, minimum: 4, maximum: 32

  validates_length_of :user_name, minimum: 4, maximum: 16
  validates_uniqueness_of :user_name

  validates_length_of :email, minimum: 3, maximum: 254
  validates_uniqueness_of :email
  validates_format_of :email, with: /@/

  validates_length_of :password, minimum: 6, maximum: 16

  validates_format_of :password, with: /\A(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])(?=.*[\W]).{6,16}\z/, 
    message: 'Password must contain at least one upper and lowercase letter, one digit, and one special character' 

  has_many :articles

  def self.account_exists?(user)
    User.where('user_name = ? OR email = ?', user.user_name, user.email).count > 0
  end
end

thinkful-wikiful-bdd/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user?, :current_user

  protected

  def params_id_valid?
    params.has_key?(:id) && params[:id].to_i > 0
  end
  
  private

  def current_user?
    current_user
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

thinkful-wikiful-bdd/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :validate_user, only: [:new, :create]

  def index
    @articles = Article.order(created_at: :desc)
  end

  def show
    if params_id_valid? && Article.exists?(params[:id])
      @articles = Article.find(params[:id])
    else
      flash[:error] = 'That article id is invalid!'
      redirect_to articles_path
    end
  end

  def new
    @article = Article.new
  end

  def create
    #logger.info "article_params: #{article_params.to_yaml}"
    #logger.info "article_params[:category_ids]: #{article_params[:category_ids].to_yaml}"

    @article = current_user.articles.create(article_params)
    if @article.save
        redirect_to articles_path(@article) and return
    end
    render :new
  end

  def search
  end

  def author
    @articles = Article.find_by_author_name(author_params[:author])
    if @articles.nil? || @articles.count == 0
      flash[:notice] = 'No articles could be found for that author'
    end
    render :search
  end

  def date 
      @articles = Article.find_by_date_published(Date.parse(date_params[:date]))
      if @articles.nil? || @articles.count == 0
        flash[:notice] = 'No articles could be found for that publish date'
      end
      render :search
  end

  # Ajax helpers.
  def autocomplete_authors
    @authors = User.order(name: :asc).select(:id, 'name AS label').where("name like ?", "%#{params[:term]}%")
    respond_to do |format|
      format.json { render json: @authors.to_json }
    end
  end

  private

  def validate_user
    if !current_user?
      flash[:error] = 'You must be logged in to create an article'
      redirect_to(articles_path) and return
    end
  end

  def author_params
    params.permit(:author)
  end

  def date_params
    params.permit(:date)
  end

  def article_params
    params.require(:article).permit(:title, :content, category_ids: [])
  end
end

thinkful-wikiful-bdd/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @articles = Article.order(created_at: :desc).limit(10)
  end
end

thinkful-wikiful-bdd/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_email(params[:email])
    if user && user.authenticate(params[:password]) # get this for free from User#has_secure_password
      session[:user_id] = user.id
      redirect_to root_url, notice: "Success! You're logged in!"
    else
      flash.now[:error] = "Aww, shucks! Email or password is invalid."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "You've been logged out! Have a nice day!"
  end
end

thinkful-wikiful-bdd/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if User.account_exists? @user
      flash[:error] = 'The username and/or email address is already in use.'
      render(:new) and return
    end
    if @user.save
      session[:user_id] = @user.id # Auto-login
      redirect_to root_url, notice: "Success! Thank you for signing up!"
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :user_name, :password, :password_confirmation)
  end
end

thinkful-wikiful-bdd/app/helpers/application_helper.rb
module ApplicationHelper
end

thinkful-wikiful-bdd/app/helpers/articles_helper.rb
module ArticlesHelper
end

thinkful-wikiful-bdd/app/helpers/home_helper.rb
module HomeHelper
end

thinkful-wikiful-bdd/app/helpers/sessions_helper.rb
module SessionsHelper
end

thinkful-wikiful-bdd/app/helpers/users_helper.rb
module UsersHelper
end

thinkful-wikiful-bdd/app/views/home/index.html.erb
<h2>Home</h2>

<%= render partial: 'shared/articles' %>

thinkful-wikiful-bdd/app/views/shared/_articles.html.erb
<%
# Don't like this, but for time constraints, and the purpose of this assignment being bdd/tdd, alas... :)
@articles = Array(@articles)
%>

<% if @articles && @articles.count > 0 %>
  <div class='article-container' style='clear:both;'>
    <% @articles.each do |article| %>
      <div class='article'>
        <div class='article-title'><%= article.title %></div>
        <div class='article-author'>Published by <%= article.user.name %> (<%= article.user.user_name %>) on <%= article.created_at.strftime('%m/%d/%Y') %></div>
        <div class='article-content'><%= truncate(article.content, length: 150) %></div>
        <div class='categories'>
          <% article.categories.each do |category| %>
          <span class='category'><%= category.name %></span>
          <% end %>
        </div>
      <div>
      <br />
    <% end %>
  </div>
<% end %>

thinkful-wikiful-bdd/app/views/shared/_main_menu.html.erb
  <div class="main-menu">
    <ul>
      <li><%= link_to('Home', root_path) %></li>     
      <% if current_user? %>
        <li><%= link_to('Log Out', logout_path) %></li>
      <% else %>
        <li><%= link_to('Log In', login_path) %></li>
        <li><%= link_to('Sign up', signup_path) %></li>
      <% end %>
      <li><%= link_to('Articles', articles_path) %></li>
       <% if current_user? %>
        <li><%= link_to('New Article', new_article_path) %></li>
      <% end %>
      <li><%= link_to('Search', articles_search_path) %></li>
    </ul>
  </div>

thinkful-wikiful-bdd/app/views/shared/_messages.html.erb
<%
messages ||= messages
%>
<% if messages && messages.errors.any? %>
  <ul>
    <% messages.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

thinkful-wikiful-bdd/app/views/users/new.html.erb
<h2>Sign Up</h2>

<%= render partial: 'shared/messages', object: @user %>

<div class="form-container">
  <%= form_for @user, url: signup_path, html:{ role: "form"} do |f| %>
    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control", placeholder: "Enter your name" %>
    </div>
    <div class="form-group">
      <%= f.label :user_name, "User Name" %>
      <%= f.text_field :user_name, class: "form-control", placeholder: "Enter a user name" %>
    </div>
    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, class: "form-control", placeholder: "Enter your email address" %>
    </div>
    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control", placeholder: "Enter your password" %>
    </div>
    <div class="form-group">
      <%= f.label :password_confirmation, "Password Confirmation" %>
      <%= f.password_field :password_confirmation, class: "form-control", placeholder: "Enter your password again" %>
    </div>
    <div class="form-actions">
      <%= f.submit "Sign Up", class: "btn btn-lg btn-primary" %>
      <%= link_to 'Cancel', root_path %>
    </div>
  <% end %>
</div>