thinkful-twetter/config/routes.rb
Twetter::Application.routes.draw do
  devise_for :users

  authenticated :user do
    resources :follows, :except => [:new, :edit, :show, :update]

    get 'twets' => 'twets#index'
    post 'twets' => 'twets#create'
    get '/:username' => 'twets#index', as: :twets_view_user
    get 'twets/:username' => 'twets#index'

    resources :retwets, :only => [:create, :destroy]
    root :to => 'follows#index', :as => :user_root
  end

  root :to => 'home#index'

end

thinkful-twetter/app/views/shared/_left_nav.html.erb
<div class="col-md-4">
  <ul class="nav nav-pills nav-stacked well text-left">
    <li>
      <%= avatar_tag user,  class: 'avatar', style: 'float:left;' %>
      <%= content_tag :strong, user.name %>
      <%= content_tag :small, '@'+user.username, class: 'clearfix' %>
    </li>
    <li>
      <table class="table table-bordered stats">
        <tbody>
          <tr>
            <td>
              <%= content_tag :h4, user.twets.count %>
              <%= content_tag :small, 'Twets', :class => "uppercase lighter" %>
            </td>
            <td>
              <%= content_tag :h4, user.follows.count %>
              <%= content_tag :small, 'Following', :class => "uppercase lighter" %>
            </td>
            <td>
              <%= content_tag :h4, Follow.where(:following_id => user.id).count %>
              <%= content_tag :small, 'Followers', :class => "uppercase lighter" %>
            </td>
        </tbody>
      </table>
    </li>
    <% if displaying_current_user? %>
      <li>
        <%= form_for (@twet || :twet), :url => twets_path,
                             :builder => InlineErrorsBuilder,
                             :method => :POST,
                             :role => :form do |f| %>
          <div class="mar-top-15">
            <%= content_tag :div, :class => f.validation_class(:content, "form-group") do %>
              <%= f.text_area :content, :placeholder => "Compose new Twet...", :class => 'form-control' %>
              <%= f.errors_for :content %>
            <% end %>

            <%= f.submit "Twet", :class => "btn btn-primary pull-right" %>
          </div>
        <% end %>
      </li>
    <% end %>
  </ul>

  <% if displaying_current_user? %>
    <ul class="nav nav-pills nav-stacked well">
      <%= nav_item("Follow", follows_path) %>
      <%= nav_item("Twet", twets_path) %>
    </ul>
  <% end %>
</div>