thinkful-twetter/config/routes.rb
Twetter::Application.routes.draw do
  devise_for :users

  authenticated :user do
    resources :follows, :except => [:new, :edit, :show, :update]

    get 'twets' => 'twets#index'
    post 'twets' => 'twets#create'
    get '/:username' => 'twets#index', as: :twets_view_user
    get 'twets/:username' => 'twets#index'

    resources :retwets, :only => [:create, :destroy]
    root :to => 'follows#index', :as => :user_root
  end

  root :to => 'home#index'

end

thinkful-twetter/app/models/twet.rb
class Twet < ActiveRecord::Base
  belongs_to :user

  has_many :retwets

  validates :content, :presence => true, :length => { :minimum => 2, :maximum => 140 }
  validates :user, :presence => true

  # Gets all twets made by the users referenced by the ids passed, starting with the
  # most recent twet made.
  #
  def self.by_user_ids(*ids)
    [:flatten!, :compact!, :uniq!].each{ |meth| ids.send(meth) }
    where(
      arel_table[:user_id]
      .in(ids)
      .or(arel_table[:id].in(
        Retwet.where(:user_id => ids).map(&:twet_id)
      ))
    ).order('created_at DESC')
  end
end

thinkful-twetter/app/controllers/twets_controller.rb
class TwetsController < ApplicationController
  # All actions in this controller require the presence of an authenticated user.
  before_filter :authenticate_user!

  # GET /twets
  #
  # This action uses the #get_twets method to set the @twets instance variable.
  #
  #   @twets # => All twets defaultly shown to the authenticated user.
  #
  def index
    twets_for
  end

  # POST /twets
  #
  # Used to create a new twet for the authenticated user based on the data passed
  # in params[:twet]. If the twet is created successfully, a success message is
  # set and we are directed to the index action. Otherwise, an error message is set,
  # the twets visible to the authenticated user are loaded into @twets and the index
  # view template is displayed.
  #
  #   @twet # => The newly created (or attempted) twet.
  #   @twets # => (only set if the twet was not created) All twets defaultly shown
  #                to the authenticated user.
  #
  #
  def create
    @twet = current_user.twets.create(twet_params)
    if @twet.valid?
      flash[:success] = "Your twet was shared"
      redirect_to :action => :index and return
    else
      get_twets
      flash[:error] = "Your twet could not be saved"
      render :action => :index and return
    end
  end

  private

  def twets_for
    if params.include? :username
      user = User.find_by_username_ignore_case params[:username]
      if user.nil?
        flash[:error] = "Username \"#{params[:username]}\" could not be found"
        render :action => :index and return
      end
      @user = user unless user.nil?
    end
  end

  # http://guides.rubyonrails.org/action_controller_overview.html#strong-parameters
  #
  # This method uses Strong Parameters to ensure that the data passed by the user
  # is appropriate. If params[:twet] does not exist or contains any key / value
  # pairs other then :content, an error will be raised and the page will return
  # a 400 'Bad Request' HTML response code.
  #
  def twet_params
    params.require(:twet).permit(:content)
  end
end

thinkful-twetter/app/helpers/twets_helper.rb
module TwetsHelper

  def twet_content_tag(tag, content)
    content_tag(tag, sub_usernames(content).html_safe)
  end

  # Returns true / false indicating whether the twet passed can be
  # retweted by the authenticated user.
  #
  def can_retwet(twet)
    if twet.user_id == current_user.id
      return false
    elsif has_retweted(twet)
      return false
    else
      return true
    end
  end

  # Returns true / false indicating whether the authenticated user
  # has already retweted the twet passed.
  #
  def has_retweted(twet)
    retwet(twet).present? ? true : false
  end

  # Returns the actual retwet instance created by the authenticated user for
  # the twet passed
  #
  def retwet(twet)
    current_user.retwets.where(:twet_id => twet.id).first
  end

  protected

  def sub_usernames(content)
    content.gsub(/\@([a-zA-z]+\b)/) { |match|
      link_to("#{match}", twets_view_user_path("#{match.from(1)}"))
    }
  end
end

thinkful-twetter/app/views/twets/_twet.html.erb
<li>
  <%= avatar_tag twet.user, class: 'avatar small', style: 'float:left;' %>
  <div>
    <%= content_tag :strong, twet.user.name, :class => 'pull-left text-middle' %>
    <%= content_tag :small, "@"+twet.user.username, :class => 'text-muted pad-10 text-middle' %>
    <%= content_tag :small, twet.created_at.strftime("%b %-d"), :class => 'text-muted text-middle pull-right' %>
    <%= twet_content_tag(:p, twet.content) %>
  </div>
  <div class="clearfix"></div>
  <% if can_retwet(twet) -%>
    <%= content_tag :div, :class => 'pull-right' do %>
    <%= form_for :retwet, :url => retwets_path,
                           :method => 'POST',
                           :role => :form do |f| %>
      <%= hidden_field_tag :return_to, request.original_url %>
      <%= f.hidden_field :twet_id, :value => twet.id.to_s %>
      <span class="glyphicon glyphicon-retweet smaller text-primary"></span>
      <%= f.submit "Retwet".html_safe, :class => 'btn btn-link smaller' %>
    <% end %>
  <% end %>
  <div class="clearfix"></div>
  <% elsif has_retweted(twet) -%>
    <%= content_tag :div, :class => 'pull-right' do %>
    <%= form_for :retwet, :url => retwet_path(retwet(twet).id),
                           :method => 'DELETE',
                           :role => :form do |f| %>
      <%= hidden_field_tag :return_to, request.original_url %>
      <span class="glyphicon glyphicon-retweet smaller text-success"></span>
      <%= f.submit 'Retweted', :class => 'btn btn-link text-success smaller' %>
    <% end %>
  <% end %>
  <div class="clearfix"></div>
  <% end -%>
</li>
<li><hr /></li>

thinkful-twetter/app/views/twets/index.html.erb
<div class="clearfix top-space small"></div>
<div class="row">

  <%= render :partial => 'shared/left_nav', :object => @user, :as => 'user' %>

  <div class="panel panel-default col-md-8 text-left">
    <div class="pull-left">
      <h4>Twets</h4>
    </div>
    <div class="clearfix"></div>
    <hr />
    <ol class="list-unstyled">
      <%= render :partial => 'twet', :collection => @user.all_twets %>
    </ol>
  </div>
</div>